baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = ["hugo-pathways-theme", "reveal-hugo"]

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "http://pdm.lsupathways.org/admin/"
  description = "Educational material for LSU Programming Digital Media"
  author = "Tate Carson"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[Languages]
[Languages.en]
title = "Educational material for LSU Programming Digital Media"
weight = 1
languageName = "English"
# staticDir = "/"



